apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: product-catalog-service
      context: ./product-catalog-service/
    - image: email-service
      context: ./email-service
deploy:
  kubectl:
    manifests:
      - k8s/*
portForward:
  - resourceType: deployment
    resourceName: product-catalog-service
    port: 80
  - resourceType: deployment
    resourceName: email-service
    port: 8080