apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: email-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: email-service