apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-db-deployment
  labels:
    app: product-catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-db
  template:
    metadata:
      labels:
        app: product-catalog-db
    spec:
      containers:
      - name: product-catalog-db
        image: mongo
        ports:
          - containerPort: 27017
        env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-catalog-db-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-catalog-db-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-db-service
spec:
  selector:
    app: product-catalog-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017    