apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-db-portal-deployment
  labels:
    app: product-catalog-db-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-db-portal
  template:
    metadata:
      labels:
        app: product-catalog-db-portal
    spec:
      containers:
      - name: product-catalog-db-portal
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: product-catalog-db-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: product-catalog-db-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: product-catalog-db-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-db-portal-service
spec:
  selector:
    app: product-catalog-db-portal
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081   